### ISSUE TITLE
Using on macos getting the following error

### ISSUE THREAD

**Issue by anika200** [mrrfv/open-android-backup#121]
## Device info

Manufacturer:Google
Android version:14
Custom ROM/rooted? No
Model:

## System info

Available disk space:
Operating system: macos 13.6.7

---

**Describe the issue below.**

Installed your requirements via Mac Ports because that is what I have and figured it should be the same as Brew. Installed your/the unzipped app bundle in ~/Applications and opened a terminal in the folder and ran the backup.sh command.
The error is as below.

`@IMac Open_Android_Backup_v1.0.18_Bundle % ./backup.sh
Whiptail is not installed, but dialog is. Defining whiptail as a function that calls dialog.
timeout is not available, can't continue. Please refer to the README for usage instructions.
`
Also may be of note:
When I installed coreutils via mac ports you get a warning about name changes which may or may not effect your app.
`--->  Some of the ports you installed have notes:
  coreutils has the following notes:
    The tools provided by GNU coreutils are prefixed with the character 'g' by default to distinguish them from the BSD
    commands.
    For example, cp becomes gcp and ls becomes gls.
    
    If you want to use the GNU tools by default, add this directory to the front of your PATH environment variable:
        /opt/local/libexec/gnubin/
`

**Comment by mrrfv** [comment]
I just pushed a fix to the `master` branch. Could you please pull the repository or download an [unstable bundle](<https://github.com/mrrfv/open-android-backup/releases/download/latest/Open_Android_Backup_Unstable_Bundle.zip>), then let me know if the problem is fixed?

**Comment by anika200** [comment]
We made progress, mostly things worked as it should, app installed, backup of apps was made but the contacts and sms were not backed up. Am I missing something? Here is the simple error at end of backup.
`Exporting contacts (as vCard), call logs as well as SMS messages (as CSV).
0.00  B 0:00:00 [0.00  B/s] [<=>                                                                                ]
mv: rename ./backup-tmp/open-android-backup-temp/open-android-backup-contact*.vcf to ./backup-tmp/Contacts/open-android-backup-contact*.vcf: No such file or directory
No contacts found on device - ignoring.
mv: rename ./backup-tmp/open-android-backup-temp/SMS_Messages.csv to ./backup-tmp/SMS/SMS_Messages.csv: No such file or directory
`

**Comment by anika200** [comment]
The model is a Pixel7. The first time run I did not see or was not aware of the second switch that needed to be turned on after you hitting the export button but it did not seem to make any difference, still have the same error. See below.

![Screenshot_20240617-153127](https://github.com/mrrfv/open-android-backup/assets/7688796/2e1744fc-2f62-4930-8d13-5387f6c54662)


![Screenshot_20240617-153141](https://github.com/mrrfv/open-android-backup/assets/7688796/687bcc8f-9bfd-4fd9-9081-db1f3ffe9d4f)

`Exporting contacts (as vCard), call logs as well as SMS messages (as CSV).
0.00  B 0:00:00 [0.00  B/s] [<=>                                                                                             ]
mv: rename ./backup-tmp/open-android-backup-temp/open-android-backup-contact*.vcf to ./backup-tmp/Contacts/open-android-backup-contact*.vcf: No such file or directory
No contacts found on device - ignoring.
mv: rename ./backup-tmp/open-android-backup-temp/SMS_Messages.csv to ./backup-tmp/SMS/SMS_Messages.csv: No such file or directory
lee@IMac Open_Android_Backup_Unstable_Bundle % 
`

**Comment by anika200** [comment]
OK I think I got it, after you hit the export data button, then you are shown the switch to allow file transfer, THEN you have to hit the back arrow and Then hit the export data button again to get it to work. So in my case I hit the export data button twice for it to work right. Maybe it was the way it was designed and I just did not read through the instructions correctly but it seems to be working on this run. Great little app.

**Comment by mrrfv** [comment]
I'll close this issue now since the problem appears to have been fixed. Thanks for reporting it.
